import type { Card } from './types';

export const cards: Card[] = [
    // NEGATIVE THOUGHTS (40+)
    // Doubt
    { id: 'n1', type: 'NEGATIVE', category: 'Doubt', text: 'I am not experienced enough.' },
    { id: 'n2', type: 'NEGATIVE', category: 'Doubt', text: 'Everyone else is smarter than me.' },
    { id: 'n3', type: 'NEGATIVE', category: 'Doubt', text: 'I will never figure this out.' },
    { id: 'n4', type: 'NEGATIVE', category: 'Doubt', text: 'My skills are outdated.' },
    { id: 'n5', type: 'NEGATIVE', category: 'Doubt', text: 'I don’t deserve this opportunity.' },
    { id: 'n6', type: 'NEGATIVE', category: 'Doubt', text: 'I am just lucky, not talented.' },
    { id: 'n7', type: 'NEGATIVE', category: 'Doubt', text: 'I will mess this up.' },
    { id: 'n8', type: 'NEGATIVE', category: 'Doubt', text: 'People will see through me.' },
    // Comparison
    { id: 'n9', type: 'NEGATIVE', category: 'Comparison', text: 'Others are getting ahead faster.' },
    { id: 'n10', type: 'NEGATIVE', category: 'Comparison', text: 'Look at their success, I have nothing.' },
    { id: 'n11', type: 'NEGATIVE', category: 'Comparison', text: 'They are naturally gifted, I am not.' },
    { id: 'n12', type: 'NEGATIVE', category: 'Comparison', text: 'I am so far behind my peers.' },
    { id: 'n13', type: 'NEGATIVE', category: 'Comparison', text: 'Why is it so easy for them?' },
    { id: 'n14', type: 'NEGATIVE', category: 'Comparison', text: 'I should be where they are by now.' },
    { id: 'n15', type: 'NEGATIVE', category: 'Comparison', text: 'My work looks terrible compared to theirs.' },
    { id: 'n16', type: 'NEGATIVE', category: 'Comparison', text: 'I will never be as good as X.' },
    // Imposter
    { id: 'n17', type: 'NEGATIVE', category: 'Imposter', text: 'I am a fraud.' },
    { id: 'n18', type: 'NEGATIVE', category: 'Imposter', text: 'They made a mistake hiring me.' },
    { id: 'n19', type: 'NEGATIVE', category: 'Imposter', text: 'I don’t belong in this room.' },
    { id: 'n20', type: 'NEGATIVE', category: 'Imposter', text: 'I have no idea what I’m doing.' },
    { id: 'n21', type: 'NEGATIVE', category: 'Imposter', text: 'Soon they will realize I’m incompetent.' },
    { id: 'n22', type: 'NEGATIVE', category: 'Imposter', text: 'I can’t handle this responsibility.' },
    { id: 'n23', type: 'NEGATIVE', category: 'Imposter', text: 'I’m just faking it.' },
    { id: 'n24', type: 'NEGATIVE', category: 'Imposter', text: 'I shouldn’t speak up.' },
    // Rejection
    { id: 'n25', type: 'NEGATIVE', category: 'Rejection', text: 'I always fail interviews.' },
    { id: 'n26', type: 'NEGATIVE', category: 'Rejection', text: 'No one wants to hire me.' },
    { id: 'n27', type: 'NEGATIVE', category: 'Rejection', text: 'I will never get an offer.' },
    { id: 'n28', type: 'NEGATIVE', category: 'Rejection', text: 'They hated me.' },
    { id: 'n29', type: 'NEGATIVE', category: 'Rejection', text: 'I am unhireable.' },
    { id: 'n30', type: 'NEGATIVE', category: 'Rejection', text: 'It’s pointless to apply.' },
    { id: 'n31', type: 'NEGATIVE', category: 'Rejection', text: 'I’m not what they are looking for.' },
    { id: 'n32', type: 'NEGATIVE', category: 'Rejection', text: 'I blew my only chance.' },
    // Perfectionism
    { id: 'n33', type: 'NEGATIVE', category: 'Perfectionism', text: 'I should be perfect before I apply.' },
    { id: 'n34', type: 'NEGATIVE', category: 'Perfectionism', text: 'If I can’t do it perfectly, I won’t do it.' },
    { id: 'n35', type: 'NEGATIVE', category: 'Perfectionism', text: 'Any mistake is a total failure.' },
    { id: 'n36', type: 'NEGATIVE', category: 'Perfectionism', text: 'I need to know everything first.' },
    { id: 'n37', type: 'NEGATIVE', category: 'Perfectionism', text: 'This isn’t good enough yet.' },
    { id: 'n38', type: 'NEGATIVE', category: 'Perfectionism', text: 'I can’t show this to anyone.' },
    { id: 'n39', type: 'NEGATIVE', category: 'Perfectionism', text: 'I’m too slow.' },
    { id: 'n40', type: 'NEGATIVE', category: 'Perfectionism', text: 'I must not ask for help.' },

    // AFFIRMATIONS (80+)
    // Growth
    { id: 'a1', type: 'AFFIRMATION', category: 'Growth', text: 'I learn fast and can adapt to challenges.' },
    { id: 'a2', type: 'AFFIRMATION', category: 'Growth', text: 'Every practice session builds my skill.' },
    { id: 'a3', type: 'AFFIRMATION', category: 'Growth', text: 'I am becoming better every day.' },
    { id: 'a4', type: 'AFFIRMATION', category: 'Growth', text: 'Challenges help me grow.' },
    { id: 'a5', type: 'AFFIRMATION', category: 'Growth', text: 'I embrace new learning opportunities.' },
    { id: 'a6', type: 'AFFIRMATION', category: 'Growth', text: 'My potential is limitless.' },
    { id: 'a7', type: 'AFFIRMATION', category: 'Growth', text: 'I can learn anything I set my mind to.' },
    { id: 'a8', type: 'AFFIRMATION', category: 'Growth', text: 'Mistakes are just data for improvement.' },
    { id: 'a9', type: 'AFFIRMATION', category: 'Growth', text: 'I am constantly evolving.' },
    { id: 'a10', type: 'AFFIRMATION', category: 'Growth', text: 'I trust my ability to figure things out.' },
    { id: 'a11', type: 'AFFIRMATION', category: 'Growth', text: 'Growth happens outside my comfort zone.' },
    { id: 'a12', type: 'AFFIRMATION', category: 'Growth', text: 'I am open to constructive feedback.' },
    { id: 'a13', type: 'AFFIRMATION', category: 'Growth', text: 'I celebrate my progress.' },
    { id: 'a14', type: 'AFFIRMATION', category: 'Growth', text: 'I am investing in myself.' },
    // Value
    { id: 'a15', type: 'AFFIRMATION', category: 'Value', text: 'My work brings value to teams.' },
    { id: 'a16', type: 'AFFIRMATION', category: 'Value', text: 'I have unique perspectives to offer.' },
    { id: 'a17', type: 'AFFIRMATION', category: 'Value', text: 'I am a valuable asset.' },
    { id: 'a18', type: 'AFFIRMATION', category: 'Value', text: 'My contributions matter.' },
    { id: 'a19', type: 'AFFIRMATION', category: 'Value', text: 'I am worthy of success.' },
    { id: 'a20', type: 'AFFIRMATION', category: 'Value', text: 'I bring positive energy.' },
    { id: 'a21', type: 'AFFIRMATION', category: 'Value', text: 'My skills are needed.' },
    { id: 'a22', type: 'AFFIRMATION', category: 'Value', text: 'I am enough just as I am.' },
    { id: 'a23', type: 'AFFIRMATION', category: 'Value', text: 'I deserve to be paid well.' },
    { id: 'a24', type: 'AFFIRMATION', category: 'Value', text: 'I am confident in my worth.' },
    { id: 'a25', type: 'AFFIRMATION', category: 'Value', text: 'I attract the right opportunities.' },
    { id: 'a26', type: 'AFFIRMATION', category: 'Value', text: 'I am proud of what I bring to the table.' },
    // Resilience
    { id: 'a27', type: 'AFFIRMATION', category: 'Resilience', text: 'Rejection protects me from the wrong fit.' },
    { id: 'a28', type: 'AFFIRMATION', category: 'Resilience', text: 'I can handle whatever comes my way.' },
    { id: 'a29', type: 'AFFIRMATION', category: 'Resilience', text: 'I bounce back stronger.' },
    { id: 'a30', type: 'AFFIRMATION', category: 'Resilience', text: 'Setbacks are temporary.' },
    { id: 'a31', type: 'AFFIRMATION', category: 'Resilience', text: 'I am resilient and tough.' },
    { id: 'a32', type: 'AFFIRMATION', category: 'Resilience', text: 'I keep going despite fear.' },
    { id: 'a33', type: 'AFFIRMATION', category: 'Resilience', text: 'I trust the timing of my life.' },
    { id: 'a34', type: 'AFFIRMATION', category: 'Resilience', text: 'One "no" brings me closer to a "yes".' },
    { id: 'a35', type: 'AFFIRMATION', category: 'Resilience', text: 'I am persistent.' },
    { id: 'a36', type: 'AFFIRMATION', category: 'Resilience', text: 'I have overcome hard things before.' },
    { id: 'a37', type: 'AFFIRMATION', category: 'Resilience', text: 'I am brave.' },
    { id: 'a38', type: 'AFFIRMATION', category: 'Resilience', text: 'I focus on what I can control.' },
    { id: 'a39', type: 'AFFIRMATION', category: 'Resilience', text: 'I am not defined by my failures.' },
    // Process
    { id: 'a40', type: 'AFFIRMATION', category: 'Process', text: 'I improve through small, consistent steps.' },
    { id: 'a41', type: 'AFFIRMATION', category: 'Process', text: 'I trust the process.' },
    { id: 'a42', type: 'AFFIRMATION', category: 'Process', text: 'Done is better than perfect.' },
    { id: 'a43', type: 'AFFIRMATION', category: 'Process', text: 'I take it one day at a time.' },
    { id: 'a44', type: 'AFFIRMATION', category: 'Process', text: 'Consistency is key.' },
    { id: 'a45', type: 'AFFIRMATION', category: 'Process', text: 'I am building a solid foundation.' },
    { id: 'a46', type: 'AFFIRMATION', category: 'Process', text: 'Small wins add up.' },
    { id: 'a47', type: 'AFFIRMATION', category: 'Process', text: 'I focus on the present moment.' },
    { id: 'a48', type: 'AFFIRMATION', category: 'Process', text: 'I am patient with myself.' },
    { id: 'a49', type: 'AFFIRMATION', category: 'Process', text: 'I enjoy the journey.' },
    { id: 'a50', type: 'AFFIRMATION', category: 'Process', text: 'I am exactly where I need to be.' },
    { id: 'a51', type: 'AFFIRMATION', category: 'Process', text: 'I am taking action.' },
    // Clarity
    { id: 'a52', type: 'AFFIRMATION', category: 'Clarity', text: 'I know what I want.' },
    { id: 'a53', type: 'AFFIRMATION', category: 'Clarity', text: 'My path is becoming clearer.' },
    { id: 'a54', type: 'AFFIRMATION', category: 'Clarity', text: 'I trust my intuition.' },
    { id: 'a55', type: 'AFFIRMATION', category: 'Clarity', text: 'I make decisions with confidence.' },
    { id: 'a56', type: 'AFFIRMATION', category: 'Clarity', text: 'I am focused on my goals.' },
    { id: 'a57', type: 'AFFIRMATION', category: 'Clarity', text: 'I see opportunities everywhere.' },
    { id: 'a58', type: 'AFFIRMATION', category: 'Clarity', text: 'I have a clear vision.' },
    { id: 'a59', type: 'AFFIRMATION', category: 'Clarity', text: 'I communicate clearly.' },
    { id: 'a60', type: 'AFFIRMATION', category: 'Clarity', text: 'I am aligned with my purpose.' },
    { id: 'a61', type: 'AFFIRMATION', category: 'Clarity', text: 'My mind is calm and clear.' },
    { id: 'a62', type: 'AFFIRMATION', category: 'Clarity', text: 'I choose positive thoughts.' },
    { id: 'a63', type: 'AFFIRMATION', category: 'Clarity', text: 'I am the architect of my life.' },
    // Gratitude
    { id: 'a64', type: 'AFFIRMATION', category: 'Gratitude', text: 'I am grateful for my skills.' },
    { id: 'a65', type: 'AFFIRMATION', category: 'Gratitude', text: 'I appreciate my journey.' },
    { id: 'a66', type: 'AFFIRMATION', category: 'Gratitude', text: 'I am thankful for new opportunities.' },
    { id: 'a67', type: 'AFFIRMATION', category: 'Gratitude', text: 'I appreciate the support I have.' },
    { id: 'a68', type: 'AFFIRMATION', category: 'Gratitude', text: 'I am grateful for my resilience.' },
    { id: 'a69', type: 'AFFIRMATION', category: 'Gratitude', text: 'I find joy in my work.' },
    { id: 'a70', type: 'AFFIRMATION', category: 'Gratitude', text: 'I am thankful for today.' },
    { id: 'a71', type: 'AFFIRMATION', category: 'Gratitude', text: 'I appreciate my own efforts.' },
    { id: 'a72', type: 'AFFIRMATION', category: 'Gratitude', text: 'I am grateful for the lessons.' },
    { id: 'a73', type: 'AFFIRMATION', category: 'Gratitude', text: 'I choose gratitude over fear.' },
    { id: 'a74', type: 'AFFIRMATION', category: 'Gratitude', text: 'I am surrounded by abundance.' },
    { id: 'a75', type: 'AFFIRMATION', category: 'Gratitude', text: 'I am lucky to be me.' },
    // Extra Affirmations to reach 80+
    { id: 'a76', type: 'AFFIRMATION', category: 'Growth', text: 'I am capable of amazing things.' },
    { id: 'a77', type: 'AFFIRMATION', category: 'Value', text: 'I believe in myself.' },
    { id: 'a78', type: 'AFFIRMATION', category: 'Resilience', text: 'I am stronger than I think.' },
    { id: 'a79', type: 'AFFIRMATION', category: 'Process', text: 'I am making progress.' },
    { id: 'a80', type: 'AFFIRMATION', category: 'Clarity', text: 'I am ready for what is next.' },
];
